# Generated by Django 3.2.9 on 2021-11-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20211127_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='name',
            field=models.CharField(default=None, max_length=50, verbose_name='Batch name'),
        ),
    ]
